### ISSUE TITLE
Log property missing in SamlSecurityService

### ISSUE THREAD

**Issue by JD-RX** [jeffwils/grails-spring-security-saml#59]
I am configuring SSO in my Grails 3.3.9 application using spring-security-saml v3.3.0 plugin. The application comes up without any issues and I can see my SSO login page. When I log in, I get server error:

`groovy.lang.MissingPropertyException: No such property: log for class: org.grails.plugin.springsecurity.saml.SamlSecurityService
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:66)
    at org.codehaus.groovy.runtime.callsite.PogoMetaClassGetPropertySite.getProperty(PogoMetaClassGetPropertySite.java:52)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:310)
    at org.grails.plugin.springsecurity.saml.SamlSecurityService.getCurrentUser(SamlSecurityService.groovy:27)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1427)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
    at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1845)
    at groovy.lang.ExpandoMetaClass.getProperty(ExpandoMetaClass.java:1155)
    at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:3773)
    at groovy.lang.ExpandoMetaClass.getProperty(ExpandoMetaClass.java:1167)
    at org.codehaus.groovy.runtime.callsite.PogoMetaClassGetPropertySite.getProperty(PogoMetaClassGetPropertySite.java:50)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:310)
    at interceptor.AllExceptRestAPIInterceptor.before(AllExceptRestAPIInterceptor.groovy:47)
    at org.grails.plugins.web.interceptors.GrailsInterceptorHandlerInterceptorAdapter.preHandle(GrailsInterceptorHandlerInterceptorAdapter.groovy:77)`

AllExceptRestAPIInterceptor is my interceptor and on line 47 I'm using springSecurityService to fetch the current user.

**Comment by valentingoebel** [comment]
Try using the latest version specified in the README. It should have fixed this problem.
