### ISSUE TITLE
ClassNotFoundException: UrlMappings

### ISSUE THREAD

**Issue by baroleg** [jeffwils/grails-spring-security-saml#65]
I'm trying to use this plugin with Grails 4.0.1. 
I set in build.gradle
```
compile 'org.grails.plugins:spring-security-saml:4.0.1'
```
and respositories according documentation. 

But have the issue: 
```
Caused by: java.lang.ClassNotFoundException: UrlMappings
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:762)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:872)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:860)
	at org.grails.plugins.BinaryGrailsPlugin.initializeProvidedArtefacts(BinaryGrailsPlugin.java:173)
	... 39 common frames omitted
```

I've checked your repository and found solution in 4.0.2 version, but when I tried to upgrade version I have another issue - package didn't find. 
Could you push new version into maven storage?

**Comment by valentingoebel** [comment]
You're right I forgot to publish it. It's available now.
